### ISSUE TITLE
Is it possible to put the polyfill in a css file so we can include it using the github url? 

### ISSUE THREAD

**Issue by starquake** [wearefractal/blink-polyfill#5]
If you make it into a css file you can use something like this:

https://raw.githubusercontent.com/davidchambers/Base64.js/master/base64.js

This can be useful to include it in a jsfiddle for example

**Comment by contra** [comment]
PR?

**Comment by pfirpfel** [comment]
You can now link to it:
https://raw.githubusercontent.com/wearefractal/blink-polyfill/master/blink.css

**Comment by starquake** [comment]
Great! Thanks!
